// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PdfGenerator;
#pragma warning restore 0105

namespace PdfGenerator
{
    public static partial class Pdf
    {
        public const string NativeLib = "pdf_generator";

        static Pdf()
        {
        }


        /// Generate PDF from input text and JSON configuration
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "generate_pdf")]
        public static extern FFIError generate_pdf(string input, string json_config, out ByteBuffer out_buffer);

        /// Free memory allocated by generate_pdf
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "free_binary_data")]
        public static extern void free_binary_data(ByteBuffer data);

    }

    public enum FFIError
    {
        Ok = 0,
        Null = 100,
        Panic = 200,
        Delegate = 300,
        Failed = 400,
        FailedInput = 401,
        FailedJson = 402,
        FailedBuffer = 403,
        FailedGeneration = 404,
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ByteBuffer
    {
        public IntPtr ptr;
        public ulong len;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
